### ISSUE TITLE
filename_format_linux does not handle templating

### ISSUE THREAD

**Issue by quotidian-ennui** [action-stars/install-tool-from-github-release#1]
Running on ubuntu-latest

```
  steps:
    - name: Install sccache
      uses: action-stars/install-tool-from-github-release@v0.2.0
      with:
        github_token: ${{ inputs.token }}
        owner: mozilla
        repository: sccache
        name: sccache
        extract: true
        version: ${{ inputs.version }}
        os_linux: unknown-linux-musl
        arch_amd64: x86_64
        subdirectory: "{name}-{version}-{arch}-{os}"
        filename_format_linux: "{name}-{version}-{arch}-{os}.{ext}"
        check_command: sccache --version
```

Note that the above _isn't strictly correct_ but is enough to illuminate the problem needs to really be : 
`"{name}-v{version}-{arch}-{os}"`

It causes this in the workflow-run logging
```
Run action-stars/install-tool-from-github-release@v0.2.0
  with:
    github_token: ***
    owner: mozilla
    repository: sccache
    name: sccache
    extract: true
    version: 0.7.0
    os_linux: unknown-linux-musl
    arch_amd64: x86_64
    subdirectory: {name}-{version}-{arch}-{os}
    filename_format_linux: {name}-{version}-{arch}-{os}.{ext}
    check_command: sccache --version
    tag_prefix: v
    arch_arm64: arm64
    os_macos: macos
    os_windows: windows
    extract_mode_linux: tar.gz
    extract_mode_macos: tar.gz
    extract_mode_windows: zip
    filename_format: {name}_{version}_{os}_{arch}.{ext}
Run action-stars/github-release-lookup@c86fa936d2dea43eac094b7d3e4ed486a93d1484
  with:
    github_token: ***
    owner: mozilla
    repository: sccache
    tag_prefix: v
    version: 0.7.0
Run ${GITHUB_ACTION_PATH}/scripts/lookup.sh
  ${GITHUB_ACTION_PATH}/scripts/lookup.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_TOKEN: ***
    OWNER: mozilla
    REPOSITORY: sccache
    VERSION: 0.7.0
    TAG_PREFIX: v
Error: The template is not valid. action-stars/install-tool-from-github-release/v0.2.0/action.yml (Line: 109, Col: 20): The following format string is invalid: [https://github.com/${{](https://github.com/$%7B%7B) inputs.owner }}/${{ inputs.repository }}/releases/download/${{ inputs.tag_prefix }}{version}/%s
```

Looks like https://github.com/action-stars/install-tool-from-github-release/blob/58e2dd20166c0eb19ab9ac4d0966c930a647ee69/action.yml#L109C56-L111 doesn't like the extra templating `{}` that is being used. (no doubt because it's nested go templating).

- The downstream _pbrisbin/setup-tool-action_ doesn't say whether templating is supported or not when you specify the linux_url_. 
- It does work if you switch to using `filename_format`, because you don't use `format()`
